language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t raiashish20/test-repo -f Dockerfile.dev .

script:
  - docker run -e CI=true raiashish20/test-repo npm run test

deploy:
 provider: elasticbeanstalk
 region: "ap-south-1"
 app: "test-app"
 env: "Testapp-env"
 bucket_name: "elasticbeanstalk-ap-south-1-671377031586"
 bucket_path: "test-app"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY
